Repository SyneticNL/MiGator, pull requests merged in 2022-10, with the labels that each got.

#4 Feature/kapstok
  README.md
  composer.json
  src/Commands/AboutCommand.php
  src/Commands/CreateCommand.php
  src/Domains/Field.php
  src/Domains/FieldInterface.php
  src/Domains/FieldTypes/BooleanType.php
  src/Domains/FieldTypes/DateTimeType.php
  src/Domains/FieldTypes/DateType.php
  src/Domains/FieldTypes/IdType.php
  src/Domains/FieldTypes/IntegerType.php
  src/Domains/FieldTypes/JsonType.php
  src/Domains/FieldTypes/StringType.php
  src/Domains/FieldTypes/TextType.php
  src/Domains/FieldTypes/UuidType.php
  src/Domains/Model.php
  src/MigatorServiceProvider.php
  src/Service/Migration.php
  src/Service/MigrationBuilder.php
  src/Service/Writer/Writer.php
  stubs/migator.create.stub
  stubs/migator.stub
  stubs/migator.update.stub
  tests/Commands/AboutCommandTest.php
  tests/Feature/Domains/ModelTest.php
  tests/Feature/WriterTest.php
  tests/Feature/fixtures/WriterTestResult.txt
  tests/Service/MigrationBuilderTest.php
  tests/TestCase.php
  tests/database/0000_00_00_000000_create_user_table.php
Labels: hacktober-accepted

#20 feature/19 phpstan config
  composer.json
  phpstan.neon.dist
  src/Domains/Model.php
  src/Service/Writer/Writer.php
Labels: bug, hacktoberfest-accepted

#21 Feature/kapstok -> main - fix phpStan issues
  src/Commands/CreateCommand.php
  src/Domains/Model.php
  src/Service/Migration.php
  src/Service/MigrationBuilder.php
  src/Service/Writer/Writer.php
Labels: hacktoberfest-accepted

#24 feat: fix phpstan issues and codestyle
  src/Domains/FieldTypes/AbstractFieldType.php
  src/Domains/FieldTypes/DateTimeType.php
Labels: hacktoberfest-accepted
